### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by sanjusci** [rayrapetyan/flask-spyne#11]
$ pip install flask-spyne
Collecting flask-spyne
  Using cached https://files.pythonhosted.org/packages/0a/a2/436b5c7d7d6916b4b881f788f2b5f9620d82a7d90eb2004a244f6e2f23c1/Flask-Spyne-0.3.1.tar.gz
Collecting flask (from flask-spyne)
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting spyne (from flask-spyne)
  Using cached https://files.pythonhosted.org/packages/0f/50/62972600a4683a57815d21aca8449c3cb5f5757fad3c1db8d7a82b6445e9/spyne-2.12.14.tar.gz
Collecting sec-wall (from flask-spyne)
  Using cached https://files.pythonhosted.org/packages/9b/70/a1b4b82187e950007959e601b5ee662d1438e45c0b80d2b1b5afd4918818/sec-wall-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w1/9kzm9vsj4f5b26rxst3wwq_40000gp/T/pip-install-xhxfqr1v/sec-wall/setup.py", line 30, in <module>
        packages = find_packages(b"src"),
      File "/Users/sanjusci/Downloads/www/demo/.env/lib/python3.6/site-packages/setuptools/__init__.py", line 62, in find
        cls._build_filter(*include)))
      File "/Users/sanjusci/Downloads/www/demo/.env/lib/python3.6/site-packages/setuptools/__init__.py", line 78, in _find_packages_iter
        package = rel_path.replace(os.path.sep, '.')
    TypeError: a bytes-like object is required, not 'str'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w1/9kzm9vsj4f5b26rxst3wwq_40000gp/T/pip-install-xhxfqr1v/sec-wall/

When I am installing on mac using python 3.6.5 version. It's giving above error. Please look into it and resolved.

**Comment by swapnilwalse** [comment]
Have the same exact issue on Mac OS Mojave, using python 3:
Using cached https://files.pythonhosted.org/packages/0a/a2/436b5c7d7d6916b4b881f788f2b5f9620d82a7d90eb2004a244f6e2f23c1/Flask-Spyne-0.3.1.tar.gz
Requirement already satisfied: flask in ./python3.7/site-packages (from Flask-Spyne) (1.0.2)
Collecting spyne (from Flask-Spyne)
  Using cached https://files.pythonhosted.org/packages/0f/50/62972600a4683a57815d21aca8449c3cb5f5757fad3c1db8d7a82b6445e9/spyne-2.12.14.tar.gz
Collecting sec-wall (from Flask-Spyne)
  Using cached https://files.pythonhosted.org/packages/9b/70/a1b4b82187e950007959e601b5ee662d1438e45c0b80d2b1b5afd4918818/sec-wall-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kk/kt22b95j39b1rd23ynstgrq40000gn/T/pip-install-s50ejayr/sec-wall/setup.py", line 30, in <module>
        packages = find_packages(b"src"),
      File "/Users/swapnilwalse/.virtualenvs/python3/lib/python3.7/site-packages/setuptools/__init__.py", line 60, in find
        cls._build_filter(*include)))
      File "/Users/swapnilwalse/.virtualenvs/python3/lib/python3.7/site-packages/setuptools/__init__.py", line 76, in _find_packages_iter
        package = rel_path.replace(os.path.sep, '.')
    TypeError: a bytes-like object is required, not 'str'

**Comment by haroldduan** [comment]
Have the same exact issue on Linux Mint 19, using python 3: 
(master)$ pip install flask-spyne
Collecting flask-spyne
  Downloading https://files.pythonhosted.org/packages/0a/a2/436b5c7d7d6916b4b881f788f2b5f9620d82a7d90eb2004a244f6e2f23c1/Flask-Spyne-0.3.1.tar.gz
Requirement already satisfied: flask in /home/haroldduan/.pyenv/versions/3.7.2/envs/env-3.7.2/lib/python3.7/site-packages (from flask-spyne) (1.0.2)
Collecting spyne (from flask-spyne)
  Downloading https://files.pythonhosted.org/packages/22/b5/d16b97357ebe959b61abe4c4692f049373b9c0724c76c660ccd36663441a/spyne-2.12.16.tar.gz (439kB)
    100% |████████████████████████████████| 440kB 20kB/s 
Collecting sec-wall (from flask-spyne)
  Downloading https://files.pythonhosted.org/packages/9b/70/a1b4b82187e950007959e601b5ee662d1438e45c0b80d2b1b5afd4918818/sec-wall-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9pg6f6d3/sec-wall/setup.py", line 30, in <module>
        packages = find_packages(b"src"),
      File "/home/haroldduan/.pyenv/versions/3.7.2/envs/env-3.7.2/lib/python3.7/site-packages/setuptools/__init__.py", line 71, in find
        cls._build_filter(*include)))
      File "/home/haroldduan/.pyenv/versions/3.7.2/envs/env-3.7.2/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in _find_packages_iter
        package = rel_path.replace(os.path.sep, '.')
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9pg6f6d3/sec-wall/

**Comment by leansy** [comment]
I found the same problem:

`
Collecting sec-wall (from flask_spyne->gsked==1.13.0.5)

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sy0ojhga/sec-wall/setup.py", line 30, in <module>
        packages = find_packages(b"src"),
      File "/home/leansy/.virtualenvs/gsked-py3/lib/python3.7/site-packages/setuptools/__init__.py", line 73, in find
        cls._build_filter(*include)))
      File "/home/leansy/.virtualenvs/gsked-py3/lib/python3.7/site-packages/setuptools/__init__.py", line 89, in _find_packages_iter
        package = rel_path.replace(os.path.sep, '.')
    TypeError: a bytes-like object is required, not 'str'
`

**Comment by daniel-butler** [comment]
Same issue here:

```
Downloading https://files.pythonhosted.org/packages/9b/70/a1b4b82187e950007959e601b5ee662d1438e45c0b80d2b1b5afd4918818/sec-wall-1.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wkmkdm6x/sec-wall/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wkmkdm6x/sec-wall/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-wkmkdm6x/sec-wall/pip-egg-info
         cwd: /tmp/pip-install-wkmkdm6x/sec-wall/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wkmkdm6x/sec-wall/setup.py", line 30, in <module>
        packages = find_packages(b"src"),
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 70, in find
        return list(cls._find_packages_iter(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 89, in _find_packages_iter
        package = rel_path.replace(os.path.sep, '.')
    TypeError: a bytes-like object is required, not 'str'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hanfeicode** [comment]
wtf 
    TypeError: a bytes-like object is required, not 'str'

win10 python3.7
不负责任的pythoner

**Comment by amatmv** [comment]
For everyone that has this error, just comment the `sec-wall` dependency from `setup.py` requirements. Since this package does not have support for Python 3.
