### ISSUE TITLE
RuntimeError: application not registered on db instance and no application bound to current context

### ISSUE THREAD

**Issue by lanmaster53** [rayrapetyan/flask-spyne#6]
I teach a class on application security and I'm trying to add a very basic, vulnerable SOAP service to an existing Flask application that I can use to demonstrate how to approach testing them. My code for the service is:

```
from spyne.protocol.soap import Soap11
from spyne.model.primitive import AnyDict, Unicode, Integer
from spyne.model.complex import Iterable

class Tools(spyne.Service):
    __service_url_path__ = '/service'
    __in_protocol__ = Soap11(validator='lxml')
    __out_protocol__ = Soap11()

    @spyne.srpc(Unicode, _returns=Iterable(AnyDict))
    def info(tid):
        query = "SELECT * FROM tools WHERE id={}"
        try:
            tools = db.session.execute(query.format(tid))
        except Exception as e:
            tools = ()
        for tool in tools:
            yield dict(tool)
```

This code sits at the bottom of my views.py file. The application is created using an application factory, and all of the routes for the application (also in views.py) are registered via blueprints in the application factory. Whenever I attempt to invoke the service I get the `RuntimeError: application not registered on db instance and no application bound to current context` error. I know it's a result of using blueprints and an application factory because I did not have this issue before I started using this approach. However, I need to use this approach moving forward. I read the merged request (https://github.com/rayrapetyan/flask-spyne/pull/2) about the `init_app` method and also read the author's examples of using Flask and Spyne together (mentioned in https://stackoverflow.com/questions/19356827/spyne-with-flask-application-context). However, his examples were architected different than my scenario and I just can't figure out how to get the app context and database into the SOAP service class object, which I'm certain is resulting in this issue. I know that this is probably not the right place to ask this question, but I do think others could benefit from the answer as well. Thank you.

**Comment by lanmaster53** [comment]
I've rearchitected my application to match that of the examples mentioned above, but I am still having the same issue. I can't figure out how to access to the same database within the Spyne Service as the Flask application. I tried passing it in the context the same way the example passed the config, but that's when I get the same error again.

**Comment by rayrapetyan** [comment]
Could you provide a link to the full code of your app and provide a stack trace where it fails?

**Comment by lanmaster53** [comment]
I don't have it posted anywhere yet, but I can provide you with the meaningful pieces. Let me know if you need anything more than below. I tried that other implementation (mentioned above) and was receiving the same error as the original way (first comment), but it required a lot more code, so I just reverted. I'm currently using the code shown below.

_views.py_

```
# other blueprint route definitions
...
from spyne.protocol.soap import Soap11
from spyne.model.primitive import AnyDict, Unicode, Integer
from spyne.model.complex import Iterable

class ToolsService(spyne.Service):
    __service_url_path__ = '/service'
    __in_protocol__ = Soap11(validator='lxml')
    __out_protocol__ = Soap11()

    @spyne.rpc(Unicode, _returns=Iterable(AnyDict))
    def info(ctx, tid):
        query = "SELECT * FROM tools WHERE id={}"
        # push app context so the db can be found
        #ctx.udc['_spyne_ctx'].push()
        try:
            tools = db.session.execute(query.format(tid))
        except Exception as e:
            tools = ()
        for tool in tools:
            yield dict(tool)
```

_\_\_init\_\_.py_

```
from flask_sqlalchemy import SQLAlchemy
from flask_spyne import Spyne
from flask_session import Session

db = SQLAlchemy()
spyne = Spyne()
sess = Session()

def create_app(config='config.Development'):

    app = Flask(__name__, static_url_path='')
    app.config.from_object(config)

    db.init_app(app)
    spyne.init_app(app)
    sess.init_app(app)

    from views import ph_bp
    app.register_blueprint(ph_bp)

    return app
```

_run.py_

```
from project import create_app

if __name__ == '__main__':
    app = create_app()
    app.run()
```

When I run the code as is, I get the following exception.

```
ERROR:spyne.util:application not registered on db instance and no application bound to current context
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 763, in _get_members_etree
    for sv in subvalue:
  File "/Users/user1/projects/myproject/project/views.py", line 612, in info
    tools = db.session.execute(query.format(tid))
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 988, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 704, in create_session
    return SignallingSession(self, **options)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 149, in __init__
    self.app = db.get_app()
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 845, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
ERROR:spyne.util:application not registered on db instance and no application bound to current context
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 676, in gen_members_parent
    ret = self._get_members_etree(ctx, cls, inst, elt)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
RuntimeError: application not registered on db instance and no application bound to current context
ERROR:spyne.util:application not registered on db instance and no application bound to current context
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 782, in _get_members_etree
    sub_name)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 463, in to_parent
    return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 814, in complex_to_parent
    add_type)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
RuntimeError: application not registered on db instance and no application bound to current context
ERROR:spyne.util:application not registered on db instance and no application bound to current context
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 676, in gen_members_parent
    ret = self._get_members_etree(ctx, cls, inst, elt)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
RuntimeError: application not registered on db instance and no application bound to current context
ERROR:spyne.server.wsgi:application not registered on db instance and no application bound to current context
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/server/wsgi.py", line 371, in handle_rpc
    self.get_out_string(p_ctx)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/server/_base.py", line 122, in get_out_string_pull
    ret = ctx.out_protocol.serialize(ctx, message=ProtocolBase.RESPONSE)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/soap/soap11.py", line 322, in serialize
    body_message_class.get_namespace())
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 463, in to_parent
    return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 814, in complex_to_parent
    add_type)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
RuntimeError: application not registered on db instance and no application bound to current context
```

It makes sense, because from what I can tell looking at the flask-spyne code, the services don't operate in the same context as the other views. They have their own "spyne" context. When I uncomment the line in the code for the service class that pushes the app context, it actually works, but only once then fails on all subsequent requests. I get the following exception:

```
ERROR:spyne.util:'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 763, in _get_members_etree
    for sv in subvalue:
  File "/Users/user1/projects/myproject/project/views.py", line 610, in info
    ctx.udc['_spyne_ctx'].push()
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR:spyne.util:'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 676, in gen_members_parent
    ret = self._get_members_etree(ctx, cls, inst, elt)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR:spyne.util:'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 782, in _get_members_etree
    sub_name)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 463, in to_parent
    return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 814, in complex_to_parent
    add_type)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR:spyne.util:'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 120, in start
    next(ret)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 676, in gen_members_parent
    ret = self._get_members_etree(ctx, cls, inst, elt)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR:spyne.server.wsgi:'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/server/wsgi.py", line 371, in handle_rpc
    self.get_out_string(p_ctx)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/server/_base.py", line 122, in get_out_string_pull
    ret = ctx.out_protocol.serialize(ctx, message=ProtocolBase.RESPONSE)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/soap/soap11.py", line 322, in serialize
    body_message_class.get_namespace())
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 463, in to_parent
    return handler(ctx, cls, inst, parent, ns, *args, **kwargs)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/protocol/xml.py", line 814, in complex_to_parent
    add_type)
  File "/Users/user1/projects/myproject/venv/lib/python2.7/site-packages/spyne/util/__init__.py", line 127, in start
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I have no idea where to go from here. I tried popping the context after the database query, but then I received an error about not being able to access a closed database. Any ideas?

**Comment by lanmaster53** [comment]
@rayrapetyan Is the above detail sufficient?

**Comment by lanmaster53** [comment]
@rayrapetyan I was able to get this working, so I'll go ahead and close this issue out. Thanks.
