### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Alexhans** [rayrapetyan/flask-spyne#9]
Hi, 

With the ongoing [Spyne for Python 3 support efforts](http://spyne.io/docs/2.11/#python-version) I was wondering if there was any plan to support python 3 as well.  

At the moment, the dependency of sec-wall seems to be one of the problems since it only works with python 2.

**Comment by gliptak** [comment]
http://sec-wall.gefira.pl/ homepage no longer accessible

**Comment by rayrapetyan** [comment]
It looks like Spyne by itself is not fully compatible with Python 3, I'm getting:
> pip install spyne
> Collecting spyne
>   Using cached https://files.pythonhosted.org/packages/0f/50/62972600a4683a57815d21aca8449c3cb5f5757fad3c1db8d7a82b6445e9/spyne-2.12.14.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-wibh69_p/spyne/setup.py", line 51, in <module>
>         LONG_DESC += "\n\n" + open('CHANGELOG.rst', 'r').read()
>       File "/ara/devel/venv_python/python3/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 1895: ordinal not in range(128)
error when trying to install.
Same described here:
https://github.com/arskom/spyne/issues/532
and here:
https://www.mail-archive.com/freebsd-pkg-fallout@freebsd.org/msg774942.html
I would wait for a more stable Python 3 support in Spyne first.

**Comment by ltuch** [comment]
It looks like recent versions of Spyne are now Python 3 compatible.

Also, it looks like there is a Python 3 port of sec-wall at https://github.com/flomincucci/sec-wall.
